user.role.authenticated:
  expected_config:
    permissions:
      - 'access content'
  update_actions:
    add:
      permissions:
        - 'configure editable user user layout overrides'
        - 'ezcontent publish view user profile'
user.role.editor:
  expected_config: { }
  update_actions:
    add:
      permissions:
        - 'ezcontent shortcut set creation'
